name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove Pre-installed Go
        run: apt-get remove --purge golang-go -y || true

      - name: Clear Go cache
        run: rm -rf /opt/hostedtoolcache/go

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          check-latest: true

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...