name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20 # Use the correct Go version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...